blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/MickaelV0/roxabi_boilerplate/tree/main/docs
    about: Check the documentation for guides and answers
  - name: Discussions
    url: https://github.com/MickaelV0/roxabi_boilerplate/discussions
    about: Ask questions and share ideas
